checklist/urls.py
from django.urls import path
from checklist import views
from django.contrib.auth import views as auth_views

app_name = 'checklist'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    #path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),  
    path('checklist-upload/<int:user_id>', views.checklist_editor, name= 'checklist_editor'),
    path('checklist-review/<int:checklist_id>', views.checklist_reviewer, name= 'checklist_reviewer'),
    path('audit-trail/<int:action_user>', views.audit_trail, name='audit_trail'),
    path('admin-audit/<int:action_user>', views.admin_audit, name='admin_audit'),
    path('delete-user/<int:user_id>/<int:action_user_id>', views.delete_user, name='delete_user'),
    path('user-management/<int:action_user>', views.users_mgmt, name='users_mgmt'),
    path('user-management/add-user/<int:action_user>', views.add_user, name='add_user'),
    path('download-audit-trail-pdf/', views.download_audit_trail_pdf, name='download_audit_trail_pdf'),
    path('download-admin-audit-pdf/', views.download_admin_audit_pdf, name='download_admin_audit_pdf'),

]

checklist/templates/checklist/add_user.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-secondary">{{ message }}</div>
{% endfor %}
{% endif %}

<div class="col-sm-12">
    <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
        <div class="card-header" style="background-color: #4962A9; color:#fff;">
            <h1>Add User</h1>
        </div>
        <div class="card-body text-dark" style=" background-position: center;">
            <form method="POST">
                {% csrf_token %}
                
                <div class="card-body">
                    {{ form.as_p }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">save</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

checklist/templates/checklist/admin_audit.html
{% extends 'base.html' %}

{% block content %}
<div style="width: 30%; margin-left: 20px; text-decoration: none;">
    <ul class="nav nav-pills nav-fill gap-2 p-1 small rounded-5 shadow-sm" id="pillNav2" role="tablist" style="background-color: #4962A9;--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
      <li class="nav-item" role="presentation">
       <a href="{% url 'checklist:users_mgmt' user.id %}"> <button class="nav-link  rounded-5" id="home-tab2"  type="button" role="tab" aria-selected="true">User Manager</button></a>
      </li>
      
    </ul>
  </div>
  <div class="col-sm-12">
    <div class="card mt-4 border border-primary">
      <div class="card-header bg-primary text-white">
        <h1>Audit Logs</h1>
      </div>
      <div class="card-body bg-light">
        <h2>Admin Audit Trail</h2>

        <div class="filter-options mb-4">
          <form method="GET" class="row g-3">
            
            <div class="col-md-3">
              <label for="start_date" class="form-label">Start Date:</label>
              <input type="date" class="form-control" name="start_date" id="start_date" value="{{ start_date|date:'Y-m-d' }}">
            </div>
            <div class="col-md-3">
              <label for="end_date" class="form-label">End Date:</label>
              <input type="date" class="form-control" name="end_date" id="end_date" value="{{ end_date|date:'Y-m-d' }}">
            </div>
            <div class="col-md-3">
              <label for="user_username" class="form-label">User:</label>
              <select class="form-select" name="user_username" id="user_username">
                <option value="">All</option>
                {% for user in users %}
                  <option value="{{ user.username }}" {% if user_username == user.username %}selected{% endif %}>{{ user.username }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-12">
              <button type="submit" class="hero-btn">Filter</button>
            </div>
          </form>
        </div>

        <div class="download-pdf  mb-4">
          <a href="{% url 'checklist:download_admin_audit_pdf' %}?start_date={{ start_date|date:'Y-m-d' }}&end_date={{ end_date|date:'Y-m-d' }}{% if user_username %}&user_username={{ user_username }}{% endif %}" class="hero-btn">Download PDF Report</a>
        </div>

        {% if audit_trail_data %}
        <div class="table-responsive">
          <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th scope="col">Event</th>
                <th scope="col">User_id</th>
                <th scope="col">Date and Time</th>
                <th scope="col">Details</th>
              
              </tr>
            </thead>
            <tbody>
              {% for entry in audit_trail_data %}
              <tr>
                <td>{{ entry.event }}</td>
                <td>{{ entry.user }}</td>
                <td>{{ entry.date_time|date:'Y-m-d H:i:s' }}</td>
                <td>{{ entry.details }}</td>
               
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
        <div class="alert alert-info">No audit trail data available.</div>
        {% endif %}
      </div>
    </div>
  </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

checklist/templates/checklist/audit_trail.html
{% extends 'base.html' %}

{% block content %}
<div style="width: 30%; margin-left: 20px; text-decoration: none;">
    <ul class="nav nav-pills nav-fill gap-2 p-1 small rounded-5 shadow-sm" id="pillNav2" role="tablist" style="background-color: #4962A9;--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
      <li class="nav-item" role="presentation">
       <a href="{% url 'checklist:users_mgmt' user.id  %}"> <button class="nav-link  rounded-5" id="home-tab2"  type="button" role="tab" aria-selected="true">User Manager</button></a>
      </li>
      
    </ul>
  </div>
<div class="col-sm-12">
    <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
        <div class="card-header" style="background-color: #4962A9; color:#fff;">
            <h1>Audit Logs</h1>
        </div>
        <div class="card-body text-dark" style=" background-position: center; background-color: beige;">
            <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button collapsed text-black" style="margin-right: 30px;width:90%; margin-left: 40px; font-size: larger;" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    Filters
                  </button>
                </h2>
                <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                  <div class="accordion-body">
            <form method="GET">
                <label for="start_date">Start Date:</label>
                <input class="form-control" type="date" id="start_date" name="start_date" value="{{ start_date|date:'Y-m-d' }}">
            
                <label for="end_date">End Date:</label>
                <input class="form-control" type="date" id="end_date" name="end_date" value="{{ end_date|date:'Y-m-d' }}">
            
                <p>
                    <label for="checklist_type">Checklist Type:</label>
                    <select class="form-control" id="checklist_type" name="checklist_type">
                      <option value="">All Types</option>
                      {% for checklist_type_value, checklist_type_label in checklist_types %}
                        <option value="{{ checklist_type_value }}" {% if checklist_type == checklist_type_value %}selected{% endif %}>{{ checklist_type_label }}</option>
                      {% endfor %}
                    </select>
                </p>
                <label for="reviewer">Reviewer:</label>
                <select class="form-control" id="reviewer" name="reviewer">
                    <option value="">All Reviewers</option>
                    {% for reviewer in reviewers %}
                        <option value="{{ reviewer.username }}" {% if reviewer_username == reviewer.username %}selected{% endif %}>{{ reviewer.username }}</option>
                    {% endfor %}
                </select>
                <p>
                    <label for="editor">Editor:</label>
                    <select class="form-control" id="editor" name="editor">
                        <option value="">All Editors</option>
                        {% for editor in editors %}
                            <option value="{{ editor.username }}" {% if editor_username == editor.username %}selected{% endif %}>{{ editor.username }}</option>
                        {% endfor %}
                    </select>
                </p>
                <p>
                    <button type="submit" class="hero-btn">Filter</button>
                    <button type="submit" name="clear_filters" value="true" class="hero-exit-btn">Clear Filters</button>
                </p>
            </form>
                  </div>
                </div>
            
        

                  </div>
            <table class="table">
                <thead>
                  <tr>
                    <th>Event</th>
                    <th>User</th>
                    <th>Date and Time</th>
                    <th>Details</th>
                  </tr>
                </thead>
                <tbody>
                    {% for entry in audit_trail_data %}
                    <tr>
                      <td>{{ entry.event }}</td>
                      <td>{{ entry.user }}</td>
                      <td>{{ entry.date_time|date:'Y-m-d H:i:s' }}</td>
                      <td>{{ entry.details }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <a href="{% url 'checklist:download_audit_trail_pdf' %}?start_date={{ start_date|date:'Y-m-d' }}&end_date={{ end_date|date:'Y-m-d' }}&checklist_type={{ checklist_type }}&reviewer={{ reviewer_username }}&editor={{ editor_username }}" class="hero-btn">Download PDF Report</a></div>
</div>
 
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
   <!--scripts-->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}

checklist/templates/checklist/delete_user.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-secondary">{{ message }}</div>
{% endfor %}
{% endif %}

<div class="col-sm-12">
    <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
        <div class="card-header" style="background-color: #4962A9; color:#fff;">
            <h1>Add User</h1>
        </div>
        <div class="card-body text-dark" style=" background-position: center;">
            <div class="card-body">
                <p>Are you sure you want to disable the user: <strong>{{ user.username }}</strong>?</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="d-flex justify-content-end">
                        <a href='#' class="btn btn-secondary mr-2">Cancel</a>
                        <button type="submit" class="btn btn-danger">Disable</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

checklist/templates/checklist/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}" >
    <link rel="stylesheet" href="{% static 'styles.css' %}" >
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" >
    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/headers/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="shortcut icon" href="https://www.fbc.co.zw/sites/default/files/favicon.ico" type="image/vnd.microsoft.icon">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0/dist/css/bootstrap-select.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0/dist/js/bootstrap-select.min.js"></script>
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">
<style>
    body {
  background-image: url(https://images.squarespace-cdn.com/content/v1/5f8f1b0bd0e167061ad431da/1611695625959-9Z93OREVKE87VWT3A0DP/374-bleu.png);
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  background-attachment: fixed;
  margin: 0;
  padding: 0;
  height: 100vh;
  }
  
     .user-box {
      align-items: center;
      width: 30%;
      padding: 9px 0;
      font-size: 14px;
      color: #0c0909;
      margin-bottom: 30px;
      border: none;
      border-bottom: 1px solid #600aeb;
      outline: none;
      background: transparent;
    }
    .user-box-date {
      align-items: center;
      width: 20%;
      padding: 9px 0;
      font-size: 14px;
      color: #0c0909;
      margin-bottom: 30px;
      border: none;
      border-bottom: 1px solid #600aeb;
      outline: none;
      background: transparent;
    }
    .user-box-select {
      align-items: center;
      width: 10%;
      padding: 9px 0;
      font-size: 15px;
      color: #0c0909;
      margin-bottom: 30px;
      border: none;
      border-bottom: 1px solid #600aeb;
      outline: none;
      background: transparent;
    }
    .hero-btn{
      display: inline-block;
      text-decoration: none;
      color: #030303;
      border: 1px solid #3b1aa5;
      padding: 9px 25px;
      font-size: 14px;
      background: transparent;
      position: relative;
      cursor: pointer;
      margin-top: 4px;
    }
    .hero-btn:hover{
      border: 1px solid #4922c7;
      background: #4962A9;
      color: #fff;
      transition: 1s;
    }
  </style>
</head>
<body style="text-align: center;background-color: aliceblue;">
    <header class="navbar navbar-light " style="padding:15px; background-color: #4962A9; margin: 30px; border-radius: 2%;">
        <a class="navbar-brand text-light" href="#">
 
          <img src="{% static 'images/thumbs/logo.png' %}" width="80" height="30"alt="">
            FBC Information Security' Checklist Review System
        </a>
        <span class="float-right mr-3 ">
            <!--a href="#"class="text-white text-decoration-none mr-3"> Home</a-->

        </span>   
    </header>
    <section  style="padding: 4rem;">
        <div class="container mt-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-sm-6" style="background-color: #4962A9; border-radius: 2%;">
                       
                            <img style="margin-top: 140px;" src="{% static 'images/thumbs/logo.png' %}" width="300" height="100" alt="">
                            
                        
                    </div>
        
                    <div class="col-sm-6">
                        <div class="card-body" style="text-align: center;">
                            <div class="form-header text-white" style="background-color: #4962A9;">
                            <h1>User credentials</h1>
                            <hr>
                            </div>
                            
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger">{{ message }}</div>
                                {% endfor %}
                            {% endif %}
                            <form method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <h3 class="mb-5 mt-2">Login into system <img src="{% static 'images/thumbs/login.png' %}" width="30" height="30"alt=""></h3>
                                    <label style="text-align: left;" for="username">Username</label>
                                    <input style="margin-bottom: 20px;" type="text" class="form-control" id="username" name="username" required>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input  style="margin-bottom: 20px;" type="password" class="form-control" id="password" name="password" required>
                                </div>
                                <hr>
                                <input type="checkbox" id="audit_trail_access" name="audit_trail_access">
                                 <label for="audit_trail_access">Admin Login</label>
<hr>
                                <button type="submit" class="hero-btn">Login</button>
                            </form>
                        </div>
        
                </div>
            </div>
                </div>
                
        
    </section>
</body>
</html>

checklist/templates/checklist/reviewer.html

{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-danger">{{ message }}</div>
{% endfor %}
{% endif %}
<div class="col-sm-12">
  <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
      <div class="card-header" style="background-color: #4962A9; color:#fff;">
          <h1>Checklist Review: {{ checklist.checklist_type}}</h1>
      </div>
      <div class="card-body text-dark" style=" background-position: center; background-color: beige;">
  <iframe  src='{{ checklist.file.url }}' width="100%" height="500"></iframe>
  <hr>
  <h2>Comments</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="hero-btn" type="submit">Submit Review</button>
  </form>
{% endblock %}

checklist/templates/checklist/uploader.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-danger">{{ message }}</div>
{% endfor %}
{% endif %}
<div class="col-sm-12">
    <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
        <div class="card-header" style="background-color: #4962A9; color:#fff;">
            <h1>Checklist Upload</h1>
        </div>
        <div class="card-body text-dark" style=" background-position: center;">
          <h5 class="card-title">Upload The Checklist</h5>
         
          <div class="align-items-center">
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="hero-btn" type="submit">Upload Checklist</button>
  </form>
          </div>
        </div>
    </div>
</div>

{% endblock %}

checklist/templates/checklist/users_mgmt.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
{% for message in messages %}
    <div class="alert alert-secondary">{{ message }}</div>
{% endfor %}
{% endif %}
<div style="width: 30%; margin-left: 20px; text-decoration: none;">
    <ul class="nav nav-pills nav-fill gap-2 p-1 small rounded-5 shadow-sm" id="pillNav2" role="tablist" style="background-color: #4962A9;--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
      <li class="nav-item" role="presentation">
        <a href="{% url 'checklist:add_user' action_user.id %}"> <button class="nav-link  rounded-5" id="home-tab2"  type="button" role="tab" aria-selected="true">Add User</button></a>
      </li>
      <li class="nav-item" role="presentation">
        <a href="{% url 'checklist:admin_audit' action_user.id %}"> <button class="nav-link  rounded-5" id="home-tab2"  type="button" role="tab" aria-selected="true">Admin Audits</button></a>
      </li>
    </ul>
  </div>
<div class="col-sm-12">
    <div class="card" style="margin-top: 40px;border: 1px solid #4962A9;">
        <div class="card-header" style="background-color: #4962A9; color:#fff;">
            <h1>System Users</h1>
        </div>
        <div class="card-body text-dark" style=" background-position: center;">
            <table class="table">
                <thead>
                    <tr>
                        <th>User ID</th>
                        <th>Username</th>
                        <th>Role</th>
                        <th>IsActive</th>
                        <th>Email</th>
                        
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                  
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.role }}</td>
                        <td>{{ user.is_active }}</td>
                        <td>{{ user.user_email }}</td>
                        <td>
                            <button type="button" class="hero-btn" data-bs-toggle="modal" data-bs-target="#editUserModal{{ user.id }}">Edit</button>
                            <a href="{% url 'checklist:delete_user' user.id action_user.id %}" class="hero-exit-btn">Disable</a>                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>

<!-- Add User Modal -->
<div class="modal fade" id="addUserModal" tabindex="-1" aria-labelledby="addUserModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addUserModalLabel">{{ add_user_modal.title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="action" value="add_user">
                <div class="modal-body">
                    {{ add_user_modal.form.as_p }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">{{ add_user_modal.button_text }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Edit User Modal -->
{% for user in users %}
<div class="modal fade" id="editUserModal{{ user.id }}" tabindex="-1" aria-labelledby="editUserModalLabel{{ user.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editUserModalLabel{{ user.id }}">{{ edit_user_modal.title }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" action="{% url 'checklist:users_mgmt' action_user.id %}">
                {% csrf_token %}
                <input type="hidden" name="action" value="edit_user">
                <input type="hidden" name="edit_user" value="{{ user.id }}">
                <div class="modal-body">
                    {{ edit_user_modal.form.as_p }}
                    
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">{{ edit_user_modal.button_text }}</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
   <!--scripts-->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}